// Garden locations data
        const portlandGardenLocations = [
            {
        id: 1,
        name: "Kennedy Garden",
        type: "Community garden",
        address: "10331 SW Kennedy St, Portland, OR",
        rating: 4.5,
        reviewCount: 13,
        openingHours: "Open ⋅ Closes 8 PM",
        coords: [45.4370, -122.7790],
        googleMapsUrl: "https://maps.google.com/?q=10331+SW+Kennedy+St,+Portland,+OR",
        description: ""
    },
    {
        id: 2,
        name: "Brentwood Community Garden",
        type: "Community garden",
        address: "6866 SE 57th Ave, Portland, OR",
        rating: 4.8,
        reviewCount: 34,
        openingHours: "Open 24 hours",
        coords: [45.4725, -122.6038],
        googleMapsUrl: "https://maps.google.com/?q=6866+SE+57th+Ave,+Portland,+OR",
        description: ""
    },
    {
        id: 3,
        name: "Woodlawn Community Garden",
        type: "Community garden",
        address: "7098 NE 11th Ave, Portland, OR",
        rating: 5.0,
        reviewCount: 6,
        coords: [45.5722, -122.6547],
        googleMapsUrl: "https://maps.google.com/?q=7098+NE+11th+Ave,+Portland,+OR",
        description: ""
    },
    {
        id: 4,
        name: "Brooklyn Community Garden",
        type: "Community garden",
        address: "SE Franklin St & SE 10th Ave, Portland, OR",
        rating: 4.6,
        reviewCount: 14,
        coords: [45.5005, -122.6540],
        googleMapsUrl: "https://maps.google.com/?q=SE+Franklin+St+%26+SE+10th+Ave,+Portland,+OR",
        description: ""
    },
    {
        id: 5,
        name: "Campbell Community Garden",
        type: "Community garden",
        address: "SE Adams St & SE 47th Ave, Portland, OR",
        rating: 4.5,
        reviewCount: 35,
        openingHours: "Open 24 hours",
        coords: [45.4938, -122.6152],
        googleMapsUrl: "https://maps.google.com/?q=SE+Adams+St+%26+SE+47th+Ave,+Portland,+OR",
        description: ""
    },
    {
        id: 6,
        name: "Lents Community Garden",
        type: "Community garden",
        address: "5208 SE 88th Ave, Portland, OR",
        rating: 4.3,
        reviewCount: 96,
        openingHours: "Open ⋅ Closes 12 AM",
        coords: [45.4846, -122.5710],
        googleMapsUrl: "https://maps.google.com/?q=5208+SE+88th+Ave,+Portland,+OR",
        description: ""
    },
    {
        id: 7,
        name: "Clinton Community Garden",
        type: "Community garden",
        address: "1815 SE Clinton St, Portland, OR",
        rating: 4.4,
        reviewCount: 7,
        openingHours: "Open 24 hours",
        coords: [45.5039, -122.6470],
        googleMapsUrl: "https://maps.google.com/?q=1815+SE+Clinton+St,+Portland,+OR",
        description: ""
    },
    {
        id: 8,
        name: "Clarendon Community Garden",
        type: "Community garden",
        address: "9235 N Van Houten Ave, Portland, OR",
        rating: 4.0,
        reviewCount: 12,
        openingHours: "Open 24 hours",
        coords: [45.6003, -122.7275],
        googleMapsUrl: "https://maps.google.com/?q=9235+N+Van+Houten+Ave,+Portland,+OR",
        description: ""
    },
    {
        id: 9,
        name: "Gilbert Heights Community Garden",
        type: "Community garden",
        address: "4209 SE 130th Ave, Portland, OR",
        rating: 4.5,
        reviewCount: 17,
        openingHours: "Open now",
        coords: [45.4915, -122.5305],
        googleMapsUrl: "https://maps.google.com/?q=4209+SE+130th+Ave,+Portland,+OR",
        description: ""
    },
    {
        id: 10,
        name: "Mt. Tabor Community Garden",
        type: "Community garden",
        address: "6001-6399 SE Lincoln St, Portland, OR",
        rating: 4.6,
        reviewCount: 62,
        openingHours: "Open now",
        coords: [45.5081, -122.5995],
        googleMapsUrl: "https://maps.google.com/?q=6001+SE+Lincoln+St,+Portland,+OR",
        description: ""
    },
    {
        id: 11,
        name: "Earl Boyles Community Garden",
        type: "Community garden",
        address: "10740 SE Francis St, Portland, OR",
        rating: 4.4,
        reviewCount: 42,
        openingHours: "Open ⋅ Closes 10 PM",
        coords: [45.4896, -122.5545],
        googleMapsUrl: "https://maps.google.com/?q=10740+SE+Francis+St,+Portland,+OR",
        description: ""
    },
    {
        id: 12,
        name: "Furey Community Garden",
        type: "Community garden",
        address: "11820 SE Reedway St, Portland, OR",
        rating: 4.3,
        reviewCount: 14,
        coords: [45.4844, -122.5382],
        googleMapsUrl: "https://maps.google.com/?q=11820+SE+Reedway+St,+Portland,+OR",
        description: ""
    },
    {
        id: 13,
        name: "Vermont Hills Community Garden",
        type: "Community garden",
        address: "6053 SW 55th Dr, Portland, OR",
        rating: 4.5,
        reviewCount: 2,
        coords: [45.4765, -122.7320],
        googleMapsUrl: "https://maps.google.com/?q=6053+SW+55th+Dr,+Portland,+OR",
        description: ""
    },
    {
        id: 14,
        name: "Sabin Community Garden",
        type: "Community garden",
        address: "NE Skidmore St & NE 19th Ave, Portland, OR",
        rating: 4.3,
        reviewCount: 16,
        openingHours: "Open ⋅ Closes 7 PM",
        coords: [45.5541, -122.6462],
        googleMapsUrl: "https://maps.google.com/?q=NE+Skidmore+St+%26+NE+19th+Ave,+Portland,+OR",
        description: ""
    },
    {
        id: 15,
        name: "Beach Community Garden",
        type: "Community garden",
        address: "4629 N Campbell Ave, Portland, OR",
        rating: 4.3,
        reviewCount: 12,
        openingHours: "Open 24 hours",
        coords: [45.5587, -122.6805],
        googleMapsUrl: "https://maps.google.com/?q=4629+N+Campbell+Ave,+Portland,+OR",
        description: ""
    },
    {
        id: 16,
        name: "Foster-Powell Community Garden",
        type: "Garden",
        address: "3519 SE 62nd Ave, Portland, OR",
        rating: 4.4,
        reviewCount: 16,
        coords: [45.4979, -122.5990],
        googleMapsUrl: "https://maps.google.com/?q=3519+SE+62nd+Ave,+Portland,+OR",
        description: ""
    },
    {
        id: 17,
        name: "Sumner Street Community Garden",
        type: "Community garden",
        address: "4624 NE Sumner St, Portland, OR",
        rating: 4.7,
        reviewCount: 7,
        coords: [45.5581, -122.6162],
        googleMapsUrl: "https://maps.google.com/?q=4624+NE+Sumner+St,+Portland,+OR",
        description: ""
    },
    {
        id: 18,
        name: "Sewallcrest Community Garden",
        type: "Community garden",
        address: "SE 31st Ave, Portland, OR",
        rating: 5.0,
        reviewCount: 4,
        coords: [45.5130, -122.6330],
        googleMapsUrl: "https://maps.google.com/?q=SE+31st+Ave,+Portland,+OR",
        description: ""
    },
    {
        id: 19,
        name: "Montavilla Walgreens Community Garden",
        type: "Garden",
        address: "8141 E Burnside St, Portland, OR",
        rating: 5.0,
        reviewCount: 21,
        openingHours: "Open 24 hours",
        coords: [45.5238, -122.5775],
        googleMapsUrl: "https://maps.google.com/?q=8141+E+Burnside+St,+Portland,+OR",
        description: ""
    }
];